version: '3.3'

services:
  nscendereco:
    volumes: 
      - vol-endereco:/logs 
    deploy:
        resources:
            limits:
              cpus: 2.00
              memory: 1024M


volumes:
  vol-endereco:
    driver_opts: 
      type: "nfs"
      o: "addr=hom-nfs-siscom.sistemas.cesan.com.br,nolock,soft,rw"
      device: ":/nfs/nsc/endereco/logs"

